export const ENTER_KEYWORDS = 'ENTER_KEYWORDS'

export const REQUEST_GET = 'REQUEST_GET'
export const REQUEST_GET_SUCCESS = 'REQUEST_GET_SUCCESS'
export const REQUEST_GET_FAILURE = 'REQUEST_GET_FAILURE'

export const SELECT_USER = 'SELECT_USER'
export const REQUEST_GET_USER_SUCCESS = 'REQUEST_GET_USER_SUCCESS'
export const REQUEST_GET_USER_REPOS_SUCCESS = 'REQUEST_GET_USER_REPOS_SUCCESS'